/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RaceService } from "../race.service";
import { RaceCreateInput } from "./RaceCreateInput";
import { Race } from "./Race";
import { RaceFindManyArgs } from "./RaceFindManyArgs";
import { RaceWhereUniqueInput } from "./RaceWhereUniqueInput";
import { RaceUpdateInput } from "./RaceUpdateInput";

export class RaceControllerBase {
  constructor(protected readonly service: RaceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Race })
  async createRace(@common.Body() data: RaceCreateInput): Promise<Race> {
    return await this.service.createRace({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Race] })
  @ApiNestedQuery(RaceFindManyArgs)
  async races(@common.Req() request: Request): Promise<Race[]> {
    const args = plainToClass(RaceFindManyArgs, request.query);
    return this.service.races({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async race(
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Race | null> {
    const result = await this.service.race({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRace(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() data: RaceUpdateInput
  ): Promise<Race | null> {
    try {
      return await this.service.updateRace({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRace(
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Race | null> {
    try {
      return await this.service.deleteRace({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
