/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Map } from "./Map";
import { MapCountArgs } from "./MapCountArgs";
import { MapFindManyArgs } from "./MapFindManyArgs";
import { MapFindUniqueArgs } from "./MapFindUniqueArgs";
import { DeleteMapArgs } from "./DeleteMapArgs";
import { MapService } from "../map.service";
@graphql.Resolver(() => Map)
export class MapResolverBase {
  constructor(protected readonly service: MapService) {}

  async _mapsMeta(
    @graphql.Args() args: MapCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Map])
  async maps(@graphql.Args() args: MapFindManyArgs): Promise<Map[]> {
    return this.service.maps(args);
  }

  @graphql.Query(() => Map, { nullable: true })
  async map(@graphql.Args() args: MapFindUniqueArgs): Promise<Map | null> {
    const result = await this.service.map(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Map)
  async deleteMap(@graphql.Args() args: DeleteMapArgs): Promise<Map | null> {
    try {
      return await this.service.deleteMap(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
