/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RaceService } from "../race.service";
import { RaceCreateInput } from "./RaceCreateInput";
import { Race } from "./Race";
import { RaceFindManyArgs } from "./RaceFindManyArgs";
import { RaceWhereUniqueInput } from "./RaceWhereUniqueInput";
import { RaceUpdateInput } from "./RaceUpdateInput";
import { LeaderboardFindManyArgs } from "../../leaderboard/base/LeaderboardFindManyArgs";
import { Leaderboard } from "../../leaderboard/base/Leaderboard";
import { LeaderboardWhereUniqueInput } from "../../leaderboard/base/LeaderboardWhereUniqueInput";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { ScoreWhereUniqueInput } from "../../score/base/ScoreWhereUniqueInput";

export class RaceControllerBase {
  constructor(protected readonly service: RaceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Race })
  async createRace(@common.Body() data: RaceCreateInput): Promise<Race> {
    return await this.service.createRace({
      data: {
        ...data,

        player: data.player
          ? {
              connect: data.player,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        track: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Race] })
  @ApiNestedQuery(RaceFindManyArgs)
  async races(@common.Req() request: Request): Promise<Race[]> {
    const args = plainToClass(RaceFindManyArgs, request.query);
    return this.service.races({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        track: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async race(
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Race | null> {
    const result = await this.service.race({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        track: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRace(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() data: RaceUpdateInput
  ): Promise<Race | null> {
    try {
      return await this.service.updateRace({
        where: params,
        data: {
          ...data,

          player: data.player
            ? {
                connect: data.player,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,
          id: true,

          player: {
            select: {
              id: true,
            },
          },

          track: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Race })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRace(
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Race | null> {
    try {
      return await this.service.deleteRace({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,

          player: {
            select: {
              id: true,
            },
          },

          track: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/leaderboards")
  @ApiNestedQuery(LeaderboardFindManyArgs)
  async findLeaderboards(
    @common.Req() request: Request,
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Leaderboard[]> {
    const query = plainToClass(LeaderboardFindManyArgs, request.query);
    const results = await this.service.findLeaderboards(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        position: true,

        race: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/leaderboards")
  async connectLeaderboards(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: LeaderboardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      leaderboards: {
        connect: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/leaderboards")
  async updateLeaderboards(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: LeaderboardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      leaderboards: {
        set: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/leaderboards")
  async disconnectLeaderboards(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: LeaderboardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      leaderboards: {
        disconnect: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/scores")
  @ApiNestedQuery(ScoreFindManyArgs)
  async findScores(
    @common.Req() request: Request,
    @common.Param() params: RaceWhereUniqueInput
  ): Promise<Score[]> {
    const query = plainToClass(ScoreFindManyArgs, request.query);
    const results = await this.service.findScores(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        race: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/scores")
  async connectScores(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        connect: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/scores")
  async updateScores(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        set: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/scores")
  async disconnectScores(
    @common.Param() params: RaceWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        disconnect: body,
      },
    };
    await this.service.updateRace({
      where: params,
      data,
      select: { id: true },
    });
  }
}
