/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Race } from "./Race";
import { RaceCountArgs } from "./RaceCountArgs";
import { RaceFindManyArgs } from "./RaceFindManyArgs";
import { RaceFindUniqueArgs } from "./RaceFindUniqueArgs";
import { CreateRaceArgs } from "./CreateRaceArgs";
import { UpdateRaceArgs } from "./UpdateRaceArgs";
import { DeleteRaceArgs } from "./DeleteRaceArgs";
import { LeaderboardFindManyArgs } from "../../leaderboard/base/LeaderboardFindManyArgs";
import { Leaderboard } from "../../leaderboard/base/Leaderboard";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { Andy } from "../../andy/base/Andy";
import { RaceService } from "../race.service";
@graphql.Resolver(() => Race)
export class RaceResolverBase {
  constructor(protected readonly service: RaceService) {}

  async _racesMeta(
    @graphql.Args() args: RaceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Race])
  async races(@graphql.Args() args: RaceFindManyArgs): Promise<Race[]> {
    return this.service.races(args);
  }

  @graphql.Query(() => Race, { nullable: true })
  async race(@graphql.Args() args: RaceFindUniqueArgs): Promise<Race | null> {
    const result = await this.service.race(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Race)
  async createRace(@graphql.Args() args: CreateRaceArgs): Promise<Race> {
    return await this.service.createRace({
      ...args,
      data: {
        ...args.data,

        player: args.data.player
          ? {
              connect: args.data.player,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Race)
  async updateRace(@graphql.Args() args: UpdateRaceArgs): Promise<Race | null> {
    try {
      return await this.service.updateRace({
        ...args,
        data: {
          ...args.data,

          player: args.data.player
            ? {
                connect: args.data.player,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Race)
  async deleteRace(@graphql.Args() args: DeleteRaceArgs): Promise<Race | null> {
    try {
      return await this.service.deleteRace(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Leaderboard], { name: "leaderboards" })
  async findLeaderboards(
    @graphql.Parent() parent: Race,
    @graphql.Args() args: LeaderboardFindManyArgs
  ): Promise<Leaderboard[]> {
    const results = await this.service.findLeaderboards(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Score], { name: "scores" })
  async findScores(
    @graphql.Parent() parent: Race,
    @graphql.Args() args: ScoreFindManyArgs
  ): Promise<Score[]> {
    const results = await this.service.findScores(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Andy, {
    nullable: true,
    name: "player",
  })
  async getPlayer(@graphql.Parent() parent: Race): Promise<Andy | null> {
    const result = await this.service.getPlayer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
