/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LeaderboardListRelationFilter } from "../../leaderboard/base/LeaderboardListRelationFilter";
import { RaceListRelationFilter } from "../../race/base/RaceListRelationFilter";
import { ScoreListRelationFilter } from "../../score/base/ScoreListRelationFilter";

@InputType()
class AndyWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LeaderboardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LeaderboardListRelationFilter)
  @IsOptional()
  @Field(() => LeaderboardListRelationFilter, {
    nullable: true,
  })
  leaderboards?: LeaderboardListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RaceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RaceListRelationFilter)
  @IsOptional()
  @Field(() => RaceListRelationFilter, {
    nullable: true,
  })
  races?: RaceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScoreListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScoreListRelationFilter)
  @IsOptional()
  @Field(() => ScoreListRelationFilter, {
    nullable: true,
  })
  scores?: ScoreListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  username?: StringNullableFilter;
}

export { AndyWhereInput as AndyWhereInput };
