/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  MaxLength,
} from "class-validator";
import { LeaderboardCreateNestedManyWithoutAndiesInput } from "./LeaderboardCreateNestedManyWithoutAndiesInput";
import { Type } from "class-transformer";
import { RaceCreateNestedManyWithoutAndiesInput } from "./RaceCreateNestedManyWithoutAndiesInput";
import { ScoreCreateNestedManyWithoutAndiesInput } from "./ScoreCreateNestedManyWithoutAndiesInput";

@InputType()
class AndyCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => LeaderboardCreateNestedManyWithoutAndiesInput,
  })
  @ValidateNested()
  @Type(() => LeaderboardCreateNestedManyWithoutAndiesInput)
  @IsOptional()
  @Field(() => LeaderboardCreateNestedManyWithoutAndiesInput, {
    nullable: true,
  })
  leaderboards?: LeaderboardCreateNestedManyWithoutAndiesInput;

  @ApiProperty({
    required: false,
    type: () => RaceCreateNestedManyWithoutAndiesInput,
  })
  @ValidateNested()
  @Type(() => RaceCreateNestedManyWithoutAndiesInput)
  @IsOptional()
  @Field(() => RaceCreateNestedManyWithoutAndiesInput, {
    nullable: true,
  })
  races?: RaceCreateNestedManyWithoutAndiesInput;

  @ApiProperty({
    required: false,
    type: () => ScoreCreateNestedManyWithoutAndiesInput,
  })
  @ValidateNested()
  @Type(() => ScoreCreateNestedManyWithoutAndiesInput)
  @IsOptional()
  @Field(() => ScoreCreateNestedManyWithoutAndiesInput, {
    nullable: true,
  })
  scores?: ScoreCreateNestedManyWithoutAndiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { AndyCreateInput as AndyCreateInput };
